use crate::types::board::board::Board;
use crate::types::color::Color;
use crate::types::moves::Move;
use crate::types::piece::{Piece, PieceType};
use crate::types::square::Square;

/// Includes the Zobrist keys that were pre-generated by the build script.
include!(concat!(env!("OUT_DIR"), "/zobrist_keys.rs"));

impl Board {
    /// Calculates the Zobrist hash for the current board position.
    pub fn hash(&mut self) -> u64 {
        if self.state.hash == 0 {
            let mut hash = 0;
            for i in 0..PieceType::COUNT {
                for j in (self.pieces[i] & self.colors[Color::White as usize]).to_squares() {
                    hash ^= ZOBRIST_KEYS.piece_keys[i][j as usize];
                }
                for j in (self.pieces[i] & self.colors[Color::Black as usize]).to_squares() {
                    hash ^= ZOBRIST_KEYS.piece_keys[i][j as usize];
                }
            }
            if self.state.color == Color::Black {
                hash ^= ZOBRIST_KEYS.black_to_move_key;
            }
            if self.state.castling.black_king() {
                hash ^= ZOBRIST_KEYS.castling_keys[0];
            }
            if self.state.castling.black_queen() {
                hash ^= ZOBRIST_KEYS.castling_keys[1];
            }
            if self.state.castling.white_king() {
                hash ^= ZOBRIST_KEYS.castling_keys[2];
            }
            if self.state.castling.white_queen() {
                hash ^= ZOBRIST_KEYS.castling_keys[3];
            }
            if self.state.en_passant != None {
                hash ^= ZOBRIST_KEYS.en_passant_keys[(self.state.en_passant.unwrap() as usize) % 8];
            }
            self.state.hash = hash;
            hash
        } else {
            self.state.hash
        }
    }
}

/// A struct containing the Zobrist keys for each possible feature of a chess position.
#[derive(Debug, Clone)]
pub struct ZobristKeys {
    /// A key for each piece on each square.
    pub piece_keys: [[u64; 64]; Piece::COUNT],
    /// A key to XOR when it is black's turn to move.
    pub black_to_move_key: u64,
    /// Keys for each of the four castling rights.
    pub castling_keys: [u64; 4],
    /// Keys for each of the eight possible en-passant files.
    pub en_passant_keys: [u64; 8],
}
